version: "3"
services:
    test:
        volumes:
            - .:/home/microblog
            - /home/microblog/.venv
        build: 
            context: .
            dockerfile: ./docker/Dockerfile_test

    dbserver:
        image: mysql:5.7
        command: --default-authentication-plugin=mysql_native_password
        volumes:
            - ./mysql:/var/lib/mysql
        environment:
            MYSQL_DATABASE: microblog
            MYSQL_RANDOM_ROOT_PASSWORD: "yes"
            MYSQL_USER: microblog
            MYSQL_PASSWORD: microblog
    
    prod:
        build:
            context: .
            dockerfile: docker/Dockerfile_prod
        container_name: microblog
        environment:
          - SECRET_KEY=production
          - DATABASE_URL=mysql+pymysql://microblog:microblog@dbserver:3306/microblog
          - FLASK_APP=microblog.py
          - FLASK_ENV=production
        ports:
            - "5000:5000"
        restart:
            "unless-stopped"
