version: 2
jobs:
    test:
        docker:
            - image: circleci/python:3.7
        
        steps:
            - checkout
            - run:
                name: Run test
                command: docker-compose up test
    
    publish:
        docker:
            - image: circleci/python:3.7
        
        steps:
            - checkout
            - setup_remote_docker
            - run:
                name: Publish docker image
                command:  | 
                    echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
                    docker build -f docker/Dockerfile_prod -t idalam/microblog
                    docker push idalam/microblog:latest


workflows:
  version: 2
  build-master:
    jobs:
        - test:
            filters:
                branches:
                    only: master
        - publish:
            requires:
                - test
            filters:
                branches:
                    only: master