version: 2
jobs:
    test:
        machine:
            image: ubuntu-1604:202007-01
        
        steps:
            - checkout
            - run:
                name: Run test
                command: docker-compose up test
    
    publish:
        machine:
            image: ubuntu-1604:202007-01
        
        steps:
            - checkout
            - run:
                name: Publish docker image
                command:  | 
                    echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
                    docker build -f docker/Dockerfile_prod -t idalam/microblog .
                    docker push idalam/microblog:latest
    
    deploy-playbook:
        machine:
            image: ubuntu-1604:202007-01
        
        steps:
            - checkout
            - run:
                name: Install
                command: |
                    python3 -m venv venv
                    . venv/bin/activate
                    make install-deploy
            
            - run:
                name: Run playbooks
                command: |
                    . venv/bin/activate
                    cd ansible
                    ansible-playbook -vvv gather_vm_instances.yml database.yml appServer.yml loadBalancer.yml monitoring.yml


workflows:
  version: 2
  build-master:
    jobs:
        - test:
            filters:
                tags:
                    only: /^v.*/
                branches:
                    ignore: /.*/
        - publish:
            requires:
                - test
            filters:
                tags:
                    only: /^v.*/
                branches:
                    ignore: /.*/
        - deploy-playbook:
            requires:
                - publish
            filters:
                tags:
                    only: /^v.*/
                branches:
                    ignore: /.*/