---
-   name: Install certbot
    apt:
        name: 
          - python-certbot-nginx
          - certbot
        state: present

-   name: Check if certificate already exists.
    stat:
        path: /etc/letsencrypt/live/{{ domain_name }}/cert.pem
    register: letsencrypt_cert

-   debug: msg="{{ letsencrypt_cert.stat.exists }}"

- name: make letsencrypt path
  shell: mkdir -p /var/www/letsencrypt

- name: Create letsencrypt certificate
  shell: certbot certonly --webroot --webroot-path /var/www/letsencrypt -m {{ letsencrypt_email }} --agree-tos -d {{ domain_name }}
  args:
    creates: /etc/letsencrypt/live/{{ domain_name }}
  when: not letsencrypt_cert.stat.exists

- name: Reload nginx
  service:
    name: nginx
    state: reloaded