FROM python:3.8

WORKDIR /home/microblog
COPY boot-test.sh .
COPY requirements ./requirements

RUN python -m venv .venv
RUN .venv/bin/pip3 install -r requirements/test.txt
RUN .venv/bin/pip3 install py pytest coverage pylint

RUN chmod +x boot-test.sh

ENTRYPOINT [ "./boot-test.sh" ]