FROM python:3.8

WORKDIR /home/microblog
COPY boot-test.sh .
COPY requirements ./requirements
COPY Makefile .

RUN python -m venv .venv
# RUN .venv/bin/pip3 make install-test
RUN . .venv/bin/activate && pip3 install -r requirements/test.txt
RUN . .venv/bin/activate && pip3 install py pytest coverage pylint

ENV prometheus_multiproc_dir /tmp

RUN chmod +x boot-test.sh

ENTRYPOINT [ "./boot-test.sh" ]