---
- name: Copy nginx.conf.j2
  template:
    src: templates/nginx.conf.j2
    dest: /etc/nginx/nginx.conf

- name: Copy load-balancer.conf.j2
  template:
    src: templates/load-balancer.conf.j2
    dest: /etc/nginx/sites-available/load-balancer.conf

- name: Link load-balancer.conf to sites-enabled
  file:
    src: /etc/nginx/sites-available/load-balancer.conf
    path: /etc/nginx/sites-enabled/load-balancer.conf
    state: link
    force: yes