apiVersion: apps/v1
kind: Deployment
metadata:
  name: microblog
spec:
  selector:
    matchLabels:
      app: microblog
  replicas: 2
  template:
    metadata:
      labels:
        app: microblog
    spec:
      containers:
      - image: idalam/microblog:flask-exporter
        imagePullPolicy: Always
        name: microblog
        ports: 
          - containerPort: 5000
        resources:
          requests:
            cou:  250m
          limits:
            cpu: 500m
        env:
          - name: SECRET_KEY
            value: production
          - name: DATABASE_URL
            value: mysql+pymysql://microblog:microblog@mysql:3306/microblog
          - name: FLASK_APP
            value: microblog.py
          - name: FLASK_ENV
            value: production
        livenessProbe:
          httpGet:
            path: /
            port: 5000