---
-   hosts: loadBalancer
    become: yes
    become_method: sudo
    remote_user: deploy
    roles:
        - docker
        - nginx
        - loadBalancer
        - https
    vars:
        ansible_python_interpreter: /usr/bin/python3.7