#Setup node exporter, prometheus och Grafana
---
-   hosts: monitoring
    become: yes
    become_method: sudo
    remote_user: azureuser
    # remote_user: deploy
    roles:
        - docker
        - node-exporter
        - prometheus
        - grafana
    vars:
        ansible_python_interpreter: /usr/bin/python3.7